trigger:
- main

resources:
- repo: self

variables:
  # tag: '$(Build.BuildId)'
  tag: 26

stages:
- stage: Build
  displayName: Build Docker Image & Publish K8S files
  jobs:
  - job: Build
    displayName: Build Docker Image
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     containerRegistry: 'thenushan-docker-hub'
    #     repository: 'thenushan/currency-exchange-devops'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile'
    #     tags: '$(tag)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: Publish K8S Files
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy Image to K8S  
  jobs:
  - job: Deploy
    displayName: Deploy Docker Image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download Artifacts
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactDirectory)'
    
    - task: KubernetesManifest@1
      displayName: K8S Deployment
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'azure-kubernetes-connection'
        namespace: 'default'
        manifests: '$(System.ArtifactDirectory)/configuration/kubernetes/deployment.yaml'
        containers: 'thenushan/currency-exchange-devops:$(tag)'
